spring:
  datasource:
    username: monohero
    password: mono-hero
    url: jdbc:mysql://localhost:3306/studentMgtApp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true